#!/usr/bin/env python3
"""agile.py - consistency engine for the Markdown tracker.

Stdlib only. Reads the YAML frontmatter of every artifact under
<tracker>/{backlog,tasks,bugs}, validates it against <tracker>/SCHEMA.md, and
regenerates <tracker>/INDEX.md deterministically. Everything project-specific -
the scopes, the agents that own them, the repositories they live in - comes
from `forge.json` via `forgecfg.py`, so this file is the same in every project.

Commands
    index                       regenerate <tracker>/INDEX.md
    lint                        validate only, print PATH:FIELD: MESSAGE
    next-id <epic|story|task|bug>   print the next free id
    show <ID>                   print JSON {path, frontmatter}

Exit codes
    0  clean
    1  fatal (unreadable file, missing directory, bad arguments)
    2  integrity issues found (index still written)
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone

sys.dont_write_bytecode = True   # never leave __pycache__ in the repo
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import forge as forgecfg  # noqa: E402

# --------------------------------------------------------------------------
# schema constants - keep in sync with <tracker>/SCHEMA.md
# The project-specific vocabulary (scopes, agents, repos) lives in forge.json.
# --------------------------------------------------------------------------

KINDS = {
    "epic": ("backlog", "EPIC", 3),
    "story": ("backlog", "STORY", 3),
    "task": ("tasks", "TASK", 4),
    "bug": ("bugs", "BUG", 4),
}

BACKLOG_STATUSES = ["draft", "groomed", "in_progress", "done", "cancelled"]
TASK_STATUSES = [
    "todo", "writing_tests", "in_progress", "review", "verify",
    "done", "blocked", "cancelled",
]
BUG_STATUSES = TASK_STATUSES + ["triage", "wontfix", "cannot_reproduce"]

BACKLOG_TRANSITIONS = {
    "draft": {"groomed", "cancelled"},
    "groomed": {"in_progress", "draft", "cancelled"},
    "in_progress": {"done", "groomed", "cancelled"},
    "done": {"in_progress"},
    "cancelled": {"draft"},
}

TASK_TRANSITIONS = {
    # qa writes the failing tests first; there is no path from todo straight
    # into implementation.
    "todo": {"writing_tests", "blocked", "cancelled"},
    "writing_tests": {"in_progress", "todo", "blocked", "cancelled"},
    "in_progress": {"review", "writing_tests", "blocked", "todo"},
    "review": {"verify", "in_progress"},
    "verify": {"done", "in_progress"},
    "blocked": {"todo", "cancelled"},
    "done": {"in_progress"},
    "cancelled": {"todo"},
}

BUG_TRANSITIONS = dict(TASK_TRANSITIONS)
BUG_TRANSITIONS["triage"] = {"todo", "wontfix", "cannot_reproduce", "blocked"}
BUG_TRANSITIONS["wontfix"] = {"triage"}
BUG_TRANSITIONS["cannot_reproduce"] = {"triage"}

PRIORITIES = ["P0", "P1", "P2", "P3"]
SEVERITIES = ["S1", "S2", "S3", "S4"]

# statuses that mean "someone is holding this right now"
CLAIMED_STATUSES = {"writing_tests", "in_progress", "review", "verify"}
# statuses that occupy a working tree
OCCUPYING_STATUSES = {"writing_tests", "in_progress", "review"}
# statuses qa owns: writing the tests, and judging the result against them
QA_STATUSES = {"writing_tests", "review", "verify"}
# statuses that require a branch to exist - qa cuts it when it writes the tests
BRANCHED_STATUSES = {"in_progress", "review", "verify"}
# statuses in which no work may start while a blocked_by target is unfinished
DEPENDENT_STATUSES = {"writing_tests", "in_progress"}
TERMINAL_STATUSES = {"done", "cancelled", "wontfix", "cannot_reproduce"}

COMMON_FIELDS = ["id", "type", "title", "status", "priority", "labels", "created", "updated"]
WORK_FIELDS = [
    "parent", "scope", "assignee", "claimed_at", "branch", "pr",
    "merge_sha", "blocked_by", "docs", "docs_waiver",
]

# statuses by which the knowledge base must have been consulted and actualised
DOCUMENTED_STATUSES = {"review", "verify", "done"}
DOCS_WAIVER_RE = re.compile(r"^NO-DOCS \(.+\)$")
BUG_EXTRA_FIELDS = ["severity", "found_in", "reported_by", "regression_of", "spawned_tasks"]

BANNER = (
    "<!-- GENERATED by .claude/scripts/agile.py - DO NOT EDIT. "
    "Run: python3 .claude/scripts/agile.py index -->"
)

ID_RE = re.compile(r"^(EPIC|STORY|TASK|BUG)-\d{3,4}$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
TS_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?Z$")
SHA_RE = re.compile(r"^[0-9a-f]{7,40}$")


# --------------------------------------------------------------------------
# frontmatter parsing - restricted grammar, no PyYAML
# --------------------------------------------------------------------------

class ParseError(Exception):
    pass


def _scalar(raw: str):
    raw = raw.strip()
    if raw == "" or raw in ("null", "~"):
        return None
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        return [_scalar(part) for part in inner.split(",")]
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
        return raw[1:-1]
    if raw in ("true", "false"):
        return raw == "true"
    return raw


def parse_frontmatter(text: str) -> dict:
    """Parse the restricted frontmatter grammar.

    Supported: `key: scalar`, `key: [a, b]`, `key:` followed by `  - item`
    lines, and full-line `#` comments. Nested maps, multiline scalars and
    anchors are deliberately unsupported - SCHEMA.md forbids them.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ParseError("file does not start with a '---' frontmatter fence")
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        raise ParseError("unterminated frontmatter block (no closing '---')")

    data: dict = {}
    key = None
    for lineno, line in enumerate(lines[1:end], start=2):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith((" ", "\t")):
            item = line.strip()
            if not item.startswith("- "):
                raise ParseError(f"line {lineno}: indented line is not a '- item'")
            if key is None or not isinstance(data.get(key), list):
                raise ParseError(f"line {lineno}: list item without a list key")
            data[key].append(_scalar(item[2:]))
            continue
        if ":" not in line:
            raise ParseError(f"line {lineno}: expected 'key: value'")
        key, _, raw = line.partition(":")
        key = key.strip()
        raw = raw.strip()
        if raw.startswith("#"):
            raw = ""
        elif " #" in raw and not raw.startswith(("\"", "'")):
            raw = raw.split(" #", 1)[0].strip()
        data[key] = [] if raw == "" else _scalar(raw)
    return data


# --------------------------------------------------------------------------
# artifact loading
# --------------------------------------------------------------------------

class Artifact:
    def __init__(self, path: str, rel: str, fm: dict, body: str):
        self.path = path
        self.rel = rel
        self.fm = fm
        self.body = body

    def __getattr__(self, name):
        return self.fm.get(name)

    @property
    def id(self) -> str:
        return self.fm.get("id") or ""

    @property
    def kind(self) -> str:
        return self.fm.get("type") or ""

    @property
    def status(self) -> str:
        return self.fm.get("status") or ""

    @property
    def prio(self) -> int:
        p = self.fm.get("priority")
        return PRIORITIES.index(p) if p in PRIORITIES else len(PRIORITIES)

    def listfield(self, name) -> list:
        v = self.fm.get(name)
        if v is None:
            return []
        return v if isinstance(v, list) else [v]

    def has_section(self, heading: str) -> bool:
        pat = re.compile(r"^##\s+" + re.escape(heading) + r"\s*$", re.MULTILINE)
        m = pat.search(self.body)
        if not m:
            return False
        rest = self.body[m.end():]
        nxt = re.search(r"^##\s+", rest, re.MULTILINE)
        chunk = rest[: nxt.start()] if nxt else rest
        for line in chunk.splitlines():
            line = line.strip()
            if not line or line in ("-", "*"):
                continue
            # `_to be filled_` and friends are placeholders, not content
            if len(line) > 1 and line.startswith("_") and line.endswith("_"):
                continue
            if line.lower().strip(".:") in ("tbd", "todo", "n/a", "none yet"):
                continue
            return True
        return False


def find_root(explicit: str | None = None) -> str:
    return forgecfg.find_root(explicit)


def tracker_dir(root: str) -> str:
    return forgecfg.load(root).tracker_dir()


def _trel(root: str) -> str:
    return forgecfg.load(root).tracker_rel


def load_all(root: str) -> tuple[list[Artifact], list[str]]:
    tracker = tracker_dir(root)
    trel = _trel(root)
    if not os.path.isdir(tracker):
        raise SystemExit(f"fatal: {tracker} does not exist")
    arts: list[Artifact] = []
    fatal: list[str] = []
    for sub in ("backlog", "tasks", "bugs"):
        d = os.path.join(tracker, sub)
        if not os.path.isdir(d):
            fatal.append(f"{trel}/{sub}: directory is missing")
            continue
        for name in sorted(os.listdir(d)):
            if not name.endswith(".md") or name.startswith("."):
                continue
            path = os.path.join(d, name)
            rel = os.path.relpath(path, root)
            try:
                with open(path, encoding="utf-8") as fh:
                    text = fh.read()
                fm = parse_frontmatter(text)
            except (OSError, ParseError) as exc:
                fatal.append(f"{rel}: {exc}")
                continue
            body = text.split("\n---", 1)[-1]
            arts.append(Artifact(path, rel, fm, body))
    return arts, fatal


# --------------------------------------------------------------------------
# validation
# --------------------------------------------------------------------------

class Issue:
    def __init__(self, rel: str, field: str, msg: str, level: str = "ERROR"):
        self.rel, self.field, self.msg, self.level = rel, field, msg, level

    def __str__(self):
        return f"{self.rel}:{self.field}: {self.level}: {self.msg}"

    def sort_key(self):
        return (0 if self.level == "ERROR" else 1, self.rel, self.field, self.msg)


def _git_sha_on_branch(root: str, repo_path: str, branch: str, sha: str) -> bool | None:
    """True/False if decidable, None if git cannot answer (no checkout, no sha)."""
    subdir = root if repo_path in (".", "") else os.path.join(root, repo_path)
    if not os.path.isdir(os.path.join(subdir, ".git")) and not os.path.isfile(
        os.path.join(subdir, ".git")
    ):
        return None
    try:
        res = subprocess.run(
            ["git", "-C", subdir, "merge-base", "--is-ancestor", sha, branch],
            capture_output=True, text=True, timeout=20,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if res.returncode == 0:
        return True
    if "Not a valid" in res.stderr or "unknown revision" in res.stderr or "malformed" in res.stderr:
        return None
    return False


def _kb_notes(root: str) -> dict[str, list[str]]:
    """Map every knowledge-base note to its lookup keys: basename, kb-relative and
    repo-relative path (all without `.md`). kb.py owns the knowledge base's own
    rules; this is only enough to resolve a ticket's `docs:` entry."""
    kb = forgecfg.load(root).kb_dir()
    keys: dict[str, list[str]] = {}
    if not os.path.isdir(kb):
        return keys
    for dirpath, dirnames, filenames in os.walk(kb):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        for name in filenames:
            if not name.endswith(".md") or name.startswith("."):
                continue
            path = os.path.join(dirpath, name)
            wrel = os.path.relpath(path, kb)
            if os.sep not in wrel:            # README.md / INDEX.md
                continue
            rel = os.path.relpath(path, root)
            for k in (name[:-3], wrel[:-3], rel[:-3]):
                keys.setdefault(k.replace(os.sep, "/"), []).append(rel)
    return keys


def validate(root: str, arts: list[Artifact], check_git: bool = True) -> list[Issue]:
    cfg = forgecfg.load(root)
    issues: list[Issue] = []

    def err(a, field, msg):
        issues.append(Issue(a.rel, field, msg))

    def warn(a, field, msg):
        issues.append(Issue(a.rel, field, msg, "WARN"))

    kb = _kb_notes(root)
    scopes = cfg.scope_names
    agents = cfg.agents
    scope_owner = cfg.scope_owner
    stale_after = timedelta(hours=cfg.stale_claim_hours)

    by_id: dict[str, Artifact] = {}
    for a in arts:
        if not a.id:
            err(a, "id", "missing")
            continue
        if not ID_RE.match(a.id):
            err(a, "id", f"'{a.id}' does not match <TYPE>-<digits>")
        if a.id in by_id:
            err(a, "id", f"duplicate id, also used by {by_id[a.id].rel}")
        else:
            by_id[a.id] = a

    for a in arts:
        kind = a.kind
        if kind not in KINDS:
            err(a, "type", f"'{kind}' is not one of {sorted(KINDS)}")
            continue
        folder, prefix, pad = KINDS[kind]

        # id / filename / folder coherence
        if a.id and not a.id.startswith(prefix + "-"):
            err(a, "id", f"type '{kind}' requires the '{prefix}-' prefix")
        if a.id and len(a.id.split("-")[-1]) != pad:
            err(a, "id", f"type '{kind}' requires a {pad}-digit number")
        if os.path.basename(os.path.dirname(a.path)) != folder:
            err(a, "type", f"'{kind}' artifacts belong in {cfg.tracker_rel}/{folder}/")
        if a.id and not os.path.basename(a.path).startswith(a.id + "-"):
            err(a, "id", f"filename must start with '{a.id}-'")

        is_backlog = kind in ("epic", "story")
        required = list(COMMON_FIELDS)
        if not is_backlog:
            required += WORK_FIELDS
        if kind == "bug":
            required += BUG_EXTRA_FIELDS
        if is_backlog:
            required += ["parent", "scope"]
        for f in required:
            if f not in a.fm:
                err(a, f, "field is missing")

        if not a.fm.get("title"):
            err(a, "title", "must not be empty")

        statuses = (
            BACKLOG_STATUSES if is_backlog
            else BUG_STATUSES if kind == "bug"
            else TASK_STATUSES
        )
        if a.status not in statuses:
            err(a, "status", f"'{a.status}' is not one of {statuses}")

        if a.fm.get("priority") not in PRIORITIES:
            err(a, "priority", f"'{a.fm.get('priority')}' is not one of {PRIORITIES}")

        for f in ("created", "updated"):
            v = a.fm.get(f)
            if v is not None and not DATE_RE.match(str(v)):
                err(a, f, f"'{v}' is not YYYY-MM-DD")

        # parent
        parent = a.fm.get("parent")
        if kind == "epic":
            if parent is not None:
                err(a, "parent", "an epic must have parent: null")
        elif kind == "story":
            if parent is None:
                err(a, "parent", "a story must name its epic")
            elif parent not in by_id:
                err(a, "parent", f"'{parent}' does not resolve to an artifact")
            elif by_id[parent].kind != "epic":
                err(a, "parent", f"'{parent}' is a {by_id[parent].kind}, expected an epic")
        else:
            if parent is None:
                err(a, "parent", "a task/bug must name its parent story, epic or bug")
            elif parent not in by_id:
                err(a, "parent", f"'{parent}' does not resolve to an artifact")
            elif by_id[parent].kind not in ("epic", "story", "bug"):
                err(a, "parent", f"'{parent}' is a {by_id[parent].kind}, not a valid parent")

        # scope
        if is_backlog:
            bad = [s for s in a.listfield("scope") if s not in scopes]
            if bad:
                err(a, "scope", f"unknown scope(s) {bad}, allowed {scopes}")
        else:
            scope = a.fm.get("scope")
            if isinstance(scope, list):
                err(a, "scope", "must be exactly one scope - split into one task per scope")
            elif scope not in scopes:
                err(a, "scope", f"'{scope}' is not one of {scopes}")

        if kind == "bug" and a.fm.get("severity") not in SEVERITIES:
            err(a, "severity", f"'{a.fm.get('severity')}' is not one of {SEVERITIES}")

        if is_backlog:
            continue

        # ---- work-artifact invariants -------------------------------------
        assignee = a.fm.get("assignee")
        claimed = a.fm.get("claimed_at")
        scope = a.fm.get("scope")

        if assignee is not None and assignee not in agents:
            err(a, "assignee", f"'{assignee}' is not one of {agents}")

        if a.status in CLAIMED_STATUSES:
            if assignee is None:
                err(a, "assignee", f"status '{a.status}' requires an assignee")
            if claimed is None:
                err(a, "claimed_at", f"status '{a.status}' requires claimed_at")

        if claimed is not None and not TS_RE.match(str(claimed)):
            err(a, "claimed_at", f"'{claimed}' is not ISO-8601 UTC (YYYY-MM-DDThh:mm:ssZ)")

        if assignee == "qa" and a.status not in QA_STATUSES:
            err(a, "assignee",
                f"qa may only hold an artifact in status {sorted(QA_STATUSES)}")
        elif assignee not in (None, "qa", "pm") and scope in scope_owner:
            if assignee not in scope_owner[scope]:
                err(a, "assignee", f"'{assignee}' may not own a '{scope}' artifact "
                                   f"(forge.json: scopes.{scope}.agent)")

        # the test-first stage is qa's, and only qa's
        if a.status == "writing_tests" and assignee not in (None, "qa"):
            err(a, "assignee", "status 'writing_tests' belongs to qa")

        if a.status in BRANCHED_STATUSES and not a.fm.get("branch"):
            err(a, "branch",
                f"status '{a.status}' requires a branch - qa cuts it in writing_tests")

        if cfg.pr_required and a.status in ("review", "verify") and not a.fm.get("pr"):
            err(a, "pr", f"status '{a.status}' requires a pr url")

        repo = cfg.repo_of_scope(scope) if scope else None
        sha = a.fm.get("merge_sha")
        if a.status == "done" and repo is not None and not sha:
            err(a, "merge_sha", "a done artifact with a code scope must record its merge sha")
        if sha and not SHA_RE.match(str(sha)):
            err(a, "merge_sha", f"'{sha}' is not a git sha")
        if sha and check_git and repo is not None:
            ok = _git_sha_on_branch(root, repo.path, repo.branch, str(sha))
            if ok is False:
                err(a, "merge_sha", f"{sha} is not reachable from {repo.path}/{repo.branch}")
            elif ok is None:
                warn(a, "merge_sha", f"could not verify {sha} against {repo.path}/{repo.branch}")

        # ---- the knowledge-base contract ----------------------------------
        # A ticket carries the notes it read at grooming and actualised at
        # close. An empty `docs:` past review is a gap, not an oversight - the
        # honest way out is a waiver, exactly as with NO-TEST.
        docs = [str(d) for d in a.listfield("docs")]
        waiver = a.fm.get("docs_waiver")
        for entry in docs:
            hits = kb.get(entry.strip().removesuffix(".md").replace(os.sep, "/"), [])
            if not hits:
                err(a, "docs", f"'{entry}' does not resolve to a note under {cfg.kb_rel}")
            elif len(hits) > 1:
                err(a, "docs", f"'{entry}' is ambiguous: {sorted(hits)}")
        if waiver is not None and not DOCS_WAIVER_RE.match(str(waiver)):
            err(a, "docs_waiver", "must read 'NO-DOCS (<reason>)' or be null")
        if docs and waiver is not None:
            err(a, "docs_waiver", "a waiver contradicts a filled docs: - drop one")
        if cfg.require_docs and a.status in DOCUMENTED_STATUSES and not docs and waiver is None:
            err(a, "docs",
                f"status '{a.status}' requires the knowledge-base notes this ticket read and "
                "actualised, or docs_waiver: NO-DOCS (<reason>)")

        # blocked_by
        for dep in a.listfield("blocked_by"):
            if dep not in by_id:
                err(a, "blocked_by", f"'{dep}' does not resolve to an artifact")
            elif a.status in DEPENDENT_STATUSES and by_id[dep].status not in TERMINAL_STATUSES:
                err(a, "blocked_by",
                    f"cannot be {a.status} while {dep} is {by_id[dep].status}")

        # bug-specific
        if kind == "bug":
            spawned = a.listfield("spawned_tasks")
            for t in spawned:
                if t not in by_id:
                    err(a, "spawned_tasks", f"'{t}' does not resolve to an artifact")
                elif by_id[t].fm.get("parent") != a.id:
                    err(a, "spawned_tasks", f"{t} must set parent: {a.id}")
            if spawned and a.status == "done":
                open_ = [t for t in spawned if t in by_id and by_id[t].status != "done"]
                if open_:
                    err(a, "status", f"cannot be done while {open_} are open")
            reg = a.fm.get("regression_of")
            if reg is not None and reg not in by_id:
                err(a, "regression_of", f"'{reg}' does not resolve to an artifact")
            if a.status in ("review", "verify") and not a.has_section("Root cause"):
                err(a, "status", "a bug must have a filled '## Root cause' before review")
            if a.status in ("wontfix", "cannot_reproduce") and not a.has_section("Log"):
                err(a, "status", f"'{a.status}' requires a justification in '## Log'")

        # stale claim
        if a.status in CLAIMED_STATUSES and claimed and TS_RE.match(str(claimed)):
            try:
                ts = datetime.strptime(str(claimed).replace("Z", "+0000"), "%Y-%m-%dT%H:%M:%S%z")
            except ValueError:
                ts = None
            if ts and datetime.now(timezone.utc) - ts > stale_after:
                warn(a, "claimed_at",
                     f"claim by {assignee} is older than {cfg.stale_claim_hours}h - pm should review")

    # blocked_by cycles
    graph = {
        a.id: [d for d in a.listfield("blocked_by") if d in by_id]
        for a in arts if a.id and a.kind in ("task", "bug")
    }
    state: dict[str, int] = {}

    def walk(node, trail):
        if state.get(node) == 2:
            return
        if state.get(node) == 1:
            cyc = " -> ".join(trail[trail.index(node):] + [node])
            issues.append(Issue(by_id[node].rel, "blocked_by", f"dependency cycle {cyc}"))
            return
        state[node] = 1
        for nxt in graph.get(node, []):
            walk(nxt, trail + [node])
        state[node] = 2

    for node in graph:
        walk(node, [])

    # one occupying artifact per working tree
    units: dict[str, list[Artifact]] = {}
    for a in arts:
        if a.kind not in ("task", "bug") or a.status not in OCCUPYING_STATUSES:
            continue
        unit = cfg.unit_of_scope(str(a.fm.get("scope")))
        if unit:
            units.setdefault(unit, []).append(a)
    for unit, holders in units.items():
        if len(holders) > 1:
            repo = cfg.repos[unit]
            where = "the repository" if repo.is_root else repo.path
            names = ", ".join(sorted(h.id for h in holders))
            for h in holders:
                err(h, "status",
                    f"{where} has one working tree; {names} occupy it at once")

    issues.sort(key=lambda i: i.sort_key())
    return issues


# --------------------------------------------------------------------------
# INDEX.md rendering
# --------------------------------------------------------------------------

def _rel_from_index(a: Artifact, root: str) -> str:
    return os.path.relpath(a.path, tracker_dir(root)).replace(os.sep, "/")


def _row(a: Artifact, root: str) -> str:
    who = a.fm.get("assignee") or "-"
    pr = a.fm.get("pr")
    prcell = f"[PR]({pr})" if pr else "-"
    scope = a.fm.get("scope") or "-"
    if isinstance(scope, list):
        scope = ", ".join(scope) or "-"
    sev = f" {a.fm.get('severity')}" if a.kind == "bug" else ""
    return (
        f"| [{a.id}]({_rel_from_index(a, root)}) | {a.fm.get('title')} | "
        f"{a.fm.get('priority')}{sev} | {scope} | {a.status} | {who} | {prcell} |"
    )


HEAD = "| ID | Title | Prio | Scope | Status | Assignee | PR |\n|---|---|---|---|---|---|---|"


def render_index(root: str, arts: list[Artifact], issues: list[Issue]) -> str:
    cfg = forgecfg.load(root)
    work = [a for a in arts if a.kind in ("task", "bug")]
    backlog = [a for a in arts if a.kind in ("epic", "story")]
    by_id = {a.id: a for a in arts if a.id}

    def key(a):
        return (a.prio, a.id)

    def blocked(a):
        if a.status == "blocked":
            return True
        return any(
            d in by_id and by_id[d].status not in TERMINAL_STATUSES
            for d in a.listfield("blocked_by")
        )

    now = sorted([a for a in work if a.status in CLAIMED_STATUSES], key=key)
    ready = sorted([a for a in work if a.status == "todo" and not blocked(a)], key=key)
    blk = sorted([a for a in work if a.status != "blocked" and blocked(a)]
                 + [a for a in work if a.status == "blocked"], key=key)
    triage = sorted([a for a in work if a.status == "triage"], key=key)
    done = sorted(
        [a for a in work if a.status == "done"],
        key=lambda a: (str(a.fm.get("updated") or ""), a.id),
        reverse=True,
    )[:15]

    out: list[str] = [BANNER, "", f"# Board - {cfg.project_name}", ""]
    counts = {
        "now": len(now), "ready": len(ready), "blocked": len(blk),
        "triage": len(triage), "done": len([a for a in work if a.status == "done"]),
    }
    out.append(
        f"Now {counts['now']} - Ready {counts['ready']} - Blocked {counts['blocked']} - "
        f"Triage {counts['triage']} - Done {counts['done']}"
    )
    out.append("")

    def section(title, items, empty):
        out.append(f"## {title}")
        out.append("")
        if not items:
            out.append(f"_{empty}_")
        else:
            out.append(HEAD)
            out.extend(_row(a, root) for a in items)
        out.append("")

    section("Now", now, "nothing in flight")
    section("Ready", ready, "nothing ready - groom something")
    section("Blocked", blk, "nothing blocked")
    section("Triage", triage, "no untriaged bugs")

    out.append("## Backlog tree")
    out.append("")
    epics = sorted([a for a in backlog if a.kind == "epic"], key=key)
    if not epics:
        out.append("_no epics yet_")
        out.append("")
    for e in epics:
        stories = sorted([a for a in backlog if a.fm.get("parent") == e.id], key=key)
        kids_of_epic = sorted([a for a in work if a.fm.get("parent") == e.id], key=key)
        tot = sum(1 for a in work if a.fm.get("parent") == e.id or
                  (a.fm.get("parent") in {s.id for s in stories}))
        dn = sum(1 for a in work if (a.fm.get("parent") == e.id or
                 a.fm.get("parent") in {s.id for s in stories}) and a.status == "done")
        out.append(
            f"- **[{e.id}]({_rel_from_index(e, root)})** {e.fm.get('title')} "
            f"- `{e.status}` {e.fm.get('priority')} ({dn}/{tot} done)"
        )
        for s in stories:
            kids = sorted([a for a in work if a.fm.get("parent") == s.id], key=key)
            sdn = sum(1 for a in kids if a.status == "done")
            out.append(
                f"  - [{s.id}]({_rel_from_index(s, root)}) {s.fm.get('title')} "
                f"- `{s.status}` ({sdn}/{len(kids)} done)"
            )
            for t in kids:
                out.append(
                    f"    - [{t.id}]({_rel_from_index(t, root)}) {t.fm.get('title')} "
                    f"- `{t.status}` {t.fm.get('scope')}"
                )
        for t in kids_of_epic:
            out.append(
                f"  - [{t.id}]({_rel_from_index(t, root)}) {t.fm.get('title')} "
                f"- `{t.status}` {t.fm.get('scope')}"
            )
    orphan_stories = sorted(
        [a for a in backlog if a.kind == "story" and a.fm.get("parent") not in
         {e.id for e in epics}], key=key)
    for s in orphan_stories:
        out.append(f"- **[{s.id}]({_rel_from_index(s, root)})** {s.fm.get('title')} "
                   f"- `{s.status}` (orphan story)")
    out.append("")

    out.append("## Recently done")
    out.append("")
    if not done:
        out.append("_nothing closed yet_")
    else:
        out.append("| ID | Title | Scope | Closed | Merge |")
        out.append("|---|---|---|---|---|")
        for a in done:
            sha = a.fm.get("merge_sha")
            out.append(
                f"| [{a.id}]({_rel_from_index(a, root)}) | {a.fm.get('title')} | "
                f"{a.fm.get('scope')} | {a.fm.get('updated')} | `{str(sha)[:8] if sha else '-'}` |"
            )
    out.append("")

    if issues:
        out.append("## Integrity")
        out.append("")
        out.append(f"`agile.py lint` reports {len(issues)} issue(s):")
        out.append("")
        for i in issues:
            out.append(f"- `{i.rel}` **{i.field}** - {i.level}: {i.msg}")
        out.append("")

    credit = cfg.credit()
    if credit:
        out += ["---", "", credit, ""]

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------

def cmd_index(root: str, arts: list[Artifact]) -> int:
    issues = validate(root, arts)
    path = os.path.join(tracker_dir(root), "INDEX.md")
    content = render_index(root, arts, issues)
    old = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            old = fh.read()
    if old != content:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
    work = [a for a in arts if a.kind in ("task", "bug")]
    errs = sum(1 for i in issues if i.level == "ERROR")
    print(
        f"index: {len(arts)} artifacts ({len(work)} work items), "
        f"{errs} error(s), {len(issues) - errs} warning(s)"
        f"{'' if old == content else ' - INDEX.md updated'}"
    )
    return 2 if issues else 0


def cmd_lint(root: str, arts: list[Artifact]) -> int:
    issues = validate(root, arts)
    for i in issues:
        print(i)
    if not issues:
        print(f"lint: clean ({len(arts)} artifacts)")
    return 2 if issues else 0


def cmd_next_id(root: str, arts: list[Artifact], kind: str) -> int:
    if kind not in KINDS:
        print(f"fatal: unknown kind '{kind}', expected one of {sorted(KINDS)}", file=sys.stderr)
        return 1
    _folder, prefix, pad = KINDS[kind]
    high = 0
    for a in arts:
        if a.id.startswith(prefix + "-"):
            try:
                high = max(high, int(a.id.split("-")[-1]))
            except ValueError:
                pass
    print(f"{prefix}-{high + 1:0{pad}d}")
    return 0


def cmd_show(root: str, arts: list[Artifact], ident: str) -> int:
    for a in arts:
        if a.id == ident:
            print(json.dumps({"path": a.rel, "frontmatter": a.fm}, indent=2, sort_keys=True))
            return 0
    print(f"fatal: no artifact with id '{ident}'", file=sys.stderr)
    return 1


USAGE = __doc__


def main(argv: list[str]) -> int:
    args = list(argv[1:])
    root_arg = None
    if "--root" in args:
        i = args.index("--root")
        try:
            root_arg = args[i + 1]
        except IndexError:
            print("fatal: --root needs a path", file=sys.stderr)
            return 1
        del args[i:i + 2]
    if not args or args[0] in ("-h", "--help", "help"):
        print(USAGE)
        return 0 if args else 1

    root = find_root(root_arg)
    arts, fatal = load_all(root)
    if fatal:
        for f in fatal:
            print(f"fatal: {f}", file=sys.stderr)
        return 1

    cmd = args[0]
    if cmd == "index":
        return cmd_index(root, arts)
    if cmd == "lint":
        return cmd_lint(root, arts)
    if cmd == "next-id":
        if len(args) < 2:
            print("fatal: next-id needs a kind (epic|story|task|bug)", file=sys.stderr)
            return 1
        return cmd_next_id(root, arts, args[1])
    if cmd == "show":
        if len(args) < 2:
            print("fatal: show needs an ID", file=sys.stderr)
            return 1
        return cmd_show(root, arts, args[1])
    print(f"fatal: unknown command '{cmd}'", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
