#!/usr/bin/env python3
"""kb.py - consistency engine for the project knowledge base.

Stdlib only. Reuses agile.py's restricted frontmatter parser, so the knowledge
base and the tracker speak the same dialect. Reads every note under
<kb>/<scope>/<type>/, validates it against <kb>/README.md, and regenerates
<kb>/INDEX.md deterministically. The scopes come from `forge.json`; the eight
types are part of the convention and are the same in every project.

Commands
    index                       regenerate <kb>/INDEX.md
    lint                        validate only, print PATH:FIELD: LEVEL: MESSAGE
    new <type> <scope> <description...>
                                create a skeleton note, print its path
                                  [--ticket TASK-0001] [--title "..."]
    find <keyword> [...]        notes matching every keyword (title, labels, body)
    for-ticket <ID>             notes bound to a ticket, plus that ticket's docs:
    show <basename|path>        print JSON {path, frontmatter, sections}
                                  (quote it - basenames contain spaces and braces)
    related <basename>          outbound links, inbound links, one-sided edges
    types                       print the legal type/scope vocabulary

Exit codes
    0  clean
    1  fatal (unreadable file, missing directory, bad arguments)
    2  integrity issues found (index still written)
"""

from __future__ import annotations

import json
import os
import re
import sys

sys.dont_write_bytecode = True   # never leave __pycache__ in the repo
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import agile     # noqa: E402  - same directory, shares the frontmatter grammar
import forge as forgecfg  # noqa: E402

# --------------------------------------------------------------------------
# vocabulary - the types are universal, the scopes come from forge.json
# --------------------------------------------------------------------------

TYPES: dict[str, list[str]] = forgecfg.KB_TYPES

NOTE_STATUSES = ["current", "superseded"]

REQUIRED_FIELDS = [
    "type", "scope", "title", "status", "created", "updated",
    "tickets", "superseded_by", "labels",
]

MAX_BASENAME = 80

BANNER = (
    "<!-- GENERATED by .claude/scripts/kb.py - DO NOT EDIT. "
    "Run: python3 .claude/scripts/kb.py index -->"
)

DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
# the description: lowercase words, separated by single spaces; a hyphen is
# allowed inside a word so `docker-compose` survives
DESC_RE = re.compile(r"^[a-z0-9]+(?:[ -][a-z0-9]+)*$")
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+?)(?:\|[^\]]*)?\]\]")
# {type} description - yyyy-mm-dd   - the braces are literal; see <kb>/README.md.
# desc is greedy so the separator binds to the last " - ", and DESC_RE then
# rejects anything that leaves a stray hyphen behind.
NAME_RE = re.compile(
    r"^\{(?P<type>[a-z-]+)\} (?P<desc>[a-z0-9][a-z0-9 -]*) - (?P<date>\d{4}-\d{2}-\d{2})$"
)


def kb_scopes(root: str) -> list[str]:
    return forgecfg.load(root).kb_scopes


def scope_locked(root: str) -> dict[str, set[str]]:
    return forgecfg.load(root).kb_locked_types


# --------------------------------------------------------------------------
# loading
# --------------------------------------------------------------------------

class Note(agile.Artifact):
    """A knowledge-base note. Inherits has_section / listfield from agile.Artifact."""

    def __init__(self, path, rel, wrel, fm, body):
        super().__init__(path, rel, fm, body)
        self.wrel = wrel                                  # relative to the kb root
        self.base = os.path.basename(rel)[:-3]            # basename, no .md
        parts = wrel.split(os.sep)
        self.dir_scope = parts[0] if len(parts) > 2 else None
        self.dir_type = parts[1] if len(parts) > 2 else None

    @property
    def title(self) -> str:
        return self.fm.get("title") or ""

    def links(self) -> list[str]:
        """Outbound wikilink targets, in document order, deduplicated."""
        seen, out = set(), []
        for m in WIKILINK_RE.finditer(self.body):
            target = m.group(1).strip()
            if target.endswith(".md"):
                target = target[:-3]
            target = os.path.basename(target)
            if target and target not in seen:
                seen.add(target)
                out.append(target)
        return out

    def related_links(self) -> list[str]:
        """Outbound links that appear under the `## Related` heading."""
        m = re.search(r"^##\s+Related\s*$", self.body, re.MULTILINE)
        if not m:
            return []
        rest = self.body[m.end():]
        nxt = re.search(r"^##\s+", rest, re.MULTILINE)
        chunk = rest[: nxt.start()] if nxt else rest
        return [os.path.basename(t.strip()[:-3] if t.strip().endswith(".md") else t.strip())
                for t in WIKILINK_RE.findall(chunk)]


def kb_dir(root: str) -> str:
    return forgecfg.load(root).kb_dir()


def load_notes(root: str) -> tuple[list[Note], list[str]]:
    kb = kb_dir(root)
    rel_kb = forgecfg.load(root).kb_rel
    if not os.path.isdir(kb):
        raise SystemExit(
            f"fatal: {kb} does not exist - create it per {rel_kb}/README.md "
            "(<scope>/<type>/ folders materialise on the first `kb.py new`)"
        )
    notes: list[Note] = []
    fatal: list[str] = []
    for dirpath, dirnames, filenames in os.walk(kb):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for name in sorted(filenames):
            if not name.endswith(".md") or name.startswith("."):
                continue
            if name in ("README.md", "INDEX.md") and os.path.samefile(dirpath, kb):
                continue
            path = os.path.join(dirpath, name)
            rel = os.path.relpath(path, root)
            wrel = os.path.relpath(path, kb)
            try:
                with open(path, encoding="utf-8") as fh:
                    text = fh.read()
                fm = agile.parse_frontmatter(text)
            except (OSError, agile.ParseError) as exc:
                fatal.append(f"{rel}: {exc}")
                continue
            body = text.split("\n---", 1)[-1]
            notes.append(Note(path, rel, wrel, fm, body))
    return notes, fatal


def resolve(notes: list[Note], ident: str) -> Note | None:
    """Resolve a basename, a kb-relative path or a repo-relative path."""
    ident = ident.strip()
    if ident.endswith(".md"):
        ident = ident[:-3]
    cands = [n for n in notes if n.base == os.path.basename(ident)]
    if len(cands) == 1:
        return cands[0]
    for n in notes:
        if ident in (n.wrel[:-3], n.rel[:-3]):
            return n
    return cands[0] if cands else None


# --------------------------------------------------------------------------
# validation
# --------------------------------------------------------------------------

def validate(root: str, notes: list[Note], arts: list[agile.Artifact]) -> list[agile.Issue]:
    issues: list[agile.Issue] = []
    SCOPES = kb_scopes(root)
    LOCKED = scope_locked(root)

    def err(n, field, msg):
        issues.append(agile.Issue(n.rel, field, msg))

    def warn(n, field, msg):
        issues.append(agile.Issue(n.rel, field, msg, "WARN"))

    ticket_ids = {a.id for a in arts if a.id}
    by_base: dict[str, Note] = {}
    for n in notes:
        if n.base in by_base:
            err(n, "filename", f"duplicate basename, also used by {by_base[n.base].rel}")
        else:
            by_base[n.base] = n

    rel_kb = forgecfg.load(root).kb_rel
    for n in notes:
        # ---- location -----------------------------------------------------
        if n.dir_scope is None:
            err(n, "path", f"a note lives at {rel_kb}/<scope>/<type>/<file>.md, never higher")
            continue
        if n.dir_scope not in SCOPES:
            err(n, "path", f"'{n.dir_scope}' is not one of {SCOPES}")
        if n.dir_type not in TYPES:
            err(n, "path", f"'{n.dir_type}' is not a known type, expected one of {sorted(TYPES)}")

        # ---- filename -----------------------------------------------------
        m = NAME_RE.match(n.base)
        if not m:
            err(n, "filename",
                "must be '{<type>} <description> - <yyyy-mm-dd>.md' - the braces around "
                "the type are literal, and the date follows a ' - ' separator")
        else:
            ftype, desc, fdate = m.group("type"), m.group("desc"), m.group("date")
            if ftype not in TYPES:
                err(n, "filename", f"'{ftype}' is not a known type, expected one of {sorted(TYPES)}")
            elif n.dir_type in TYPES and ftype != n.dir_type:
                err(n, "filename", f"'{{{ftype}}}' contradicts the folder '{n.dir_type}'")
            if not DESC_RE.match(desc):
                err(n, "filename", f"description '{desc}' must be lowercase words separated by spaces")
            if n.fm.get("created") and str(n.fm["created"]) != fdate:
                err(n, "created", f"'{n.fm['created']}' contradicts the date in the filename ({fdate})")
        if len(os.path.basename(n.rel)) > MAX_BASENAME:
            err(n, "filename", f"{len(os.path.basename(n.rel))} chars, the limit is {MAX_BASENAME}")

        # ---- frontmatter --------------------------------------------------
        for f in REQUIRED_FIELDS:
            if f not in n.fm:
                err(n, f, "field is missing")

        ntype = n.fm.get("type")
        if ntype not in TYPES:
            err(n, "type", f"'{ntype}' is not one of {sorted(TYPES)}")
        elif n.dir_type in TYPES and ntype != n.dir_type:
            err(n, "type", f"'{ntype}' contradicts the folder '{n.dir_type}'")

        nscope = n.fm.get("scope")
        if nscope not in SCOPES:
            err(n, "scope", f"'{nscope}' is not one of {SCOPES}")
        elif n.dir_scope in SCOPES and nscope != n.dir_scope:
            err(n, "scope", f"'{nscope}' contradicts the folder '{n.dir_scope}'")

        if ntype in LOCKED and nscope not in LOCKED[ntype]:
            err(n, "scope", f"type '{ntype}' may only live in {sorted(LOCKED[ntype])}")

        if not n.title:
            err(n, "title", "must not be empty")
        elif len(n.title) < 12:
            warn(n, "title", "state the finding as a sentence, not a one-word label")

        if n.status not in NOTE_STATUSES:
            err(n, "status", f"'{n.status}' is not one of {NOTE_STATUSES}")

        for f in ("created", "updated"):
            v = n.fm.get(f)
            if v is None:
                err(n, f, "must be a date")
            elif not DATE_RE.match(str(v)):
                err(n, f, f"'{v}' is not YYYY-MM-DD")
        cre, upd = str(n.fm.get("created")), str(n.fm.get("updated"))
        if DATE_RE.match(cre) and DATE_RE.match(upd) and upd < cre:
            err(n, "updated", f"'{upd}' precedes created '{cre}'")

        # ---- tickets ------------------------------------------------------
        tickets = n.listfield("tickets")
        if not tickets:
            warn(n, "tickets", "no ticket recorded - which work produced or confirmed this?")
        for t in tickets:
            if t not in ticket_ids:
                err(n, "tickets", f"'{t}' does not resolve to an artifact in the tracker")

        # ---- supersession -------------------------------------------------
        sb = n.fm.get("superseded_by")
        if n.status == "superseded":
            if not sb:
                err(n, "superseded_by", "a superseded note must point at its replacement")
            elif not resolve(notes, str(sb)):
                err(n, "superseded_by", f"'{sb}' does not resolve to a note")
        elif sb:
            err(n, "superseded_by", "set only when status is 'superseded'")

        # ---- body ---------------------------------------------------------
        for heading in TYPES.get(ntype, []) if ntype in TYPES else []:
            if not re.search(r"^##\s+" + re.escape(heading) + r"\s*$", n.body, re.MULTILINE):
                err(n, "body", f"missing section '## {heading}'")
            elif not n.has_section(heading):
                err(n, "body", f"section '## {heading}' is empty or a placeholder")
        if not re.search(r"^##\s+Related\s*$", n.body, re.MULTILINE):
            err(n, "body", "missing section '## Related' - keep it with '- _none yet_' if empty")

        # ---- links --------------------------------------------------------
        for target in n.links():
            if target == n.base:
                err(n, "links", "a note must not link to itself")
            elif target not in by_base:
                err(n, "links", f"[[{target}]] does not resolve to a note")

    # ---- reciprocity and orphans ------------------------------------------
    inbound: dict[str, set[str]] = {n.base: set() for n in notes}
    for n in notes:
        for t in n.links():
            if t in inbound and t != n.base:
                inbound[t].add(n.base)
    for n in notes:
        for t in n.related_links():
            if t in by_base and n.base not in by_base[t].related_links():
                warn(n, "links", f"[[{t}]] is a one-sided edge - add the matching line there")
        if not n.links() and not inbound[n.base] and len(notes) > 1:
            warn(n, "links", "orphan - no note links to it and it links to nothing")

    return sorted(issues, key=lambda i: (i.rel, i.field))


def ticket_docs_issues(root: str, notes: list[Note], arts: list[agile.Artifact]) -> list[agile.Issue]:
    """The tracker half of the contract, reported alongside the knowledge-base half.

    agile.py owns the authoritative check (it is what /agile:work and
    /agile:close run); this mirrors it so `kb.py lint` alone is enough to see
    a broken ticket->note edge.
    """
    issues: list[agile.Issue] = []
    for a in arts:
        if a.kind not in ("task", "bug"):
            continue
        for entry in a.listfield("docs"):
            if not resolve(notes, str(entry)):
                issues.append(agile.Issue(a.rel, "docs",
                                          f"'{entry}' does not resolve to a knowledge-base note"))
    return issues


# --------------------------------------------------------------------------
# INDEX.md
# --------------------------------------------------------------------------

def render_index(root: str, notes: list[Note], issues: list[agile.Issue]) -> str:
    cfg = forgecfg.load(root)
    SCOPES = cfg.kb_scopes
    LOCKED = cfg.kb_locked_types
    current = [n for n in notes if n.status != "superseded"]
    gone = [n for n in notes if n.status == "superseded"]

    out = [BANNER, "", "# Knowledge index", "",
           f"What we know about {cfg.project_name}, by scope and type. The convention is in",
           "[`README.md`](README.md); the graph lives in each note's `## Related`",
           "section, not here.", ""]

    out.append(f"{len(notes)} note(s): {len(current)} current, {len(gone)} superseded.")
    out.append("")

    # coverage matrix - zeros are the point, they are the backlog
    out.append("## Coverage")
    out.append("")
    out.append("| Type | " + " | ".join(SCOPES) + " |")
    out.append("|---|" + "---|" * len(SCOPES))
    for t in sorted(TYPES):
        cells = []
        for s in SCOPES:
            if t in LOCKED and s not in LOCKED[t]:
                cells.append("&mdash;")
                continue
            k = sum(1 for n in current if n.fm.get("type") == t and n.fm.get("scope") == s)
            cells.append(str(k) if k else "_0_")
        out.append(f"| `{t}` | " + " | ".join(cells) + " |")
    out.append("")

    for s in SCOPES:
        here = [n for n in current if n.fm.get("scope") == s]
        out.append(f"## {s}")
        out.append("")
        if not here:
            out.append("_No notes yet._")
            out.append("")
            continue
        for t in sorted(TYPES):
            group = sorted((n for n in here if n.fm.get("type") == t), key=lambda n: n.base)
            if not group:
                continue
            out.append(f"### {t}")
            out.append("")
            for n in group:
                tickets = ", ".join(f"`{x}`" for x in n.listfield("tickets")) or "&ndash;"
                labels = ", ".join(f"`{x}`" for x in n.listfield("labels"))
                bits = [f"updated {n.fm.get('updated')}", tickets]
                if labels:
                    bits.append(labels)
                link = n.wrel.replace(os.sep, "/")
                out.append(f"- [{n.title}]({link}) &middot; `[[{n.base}]]` &middot; "
                           + " &middot; ".join(bits))
            out.append("")

    if gone:
        out.append("## Superseded")
        out.append("")
        for n in sorted(gone, key=lambda n: n.base):
            link = n.wrel.replace(os.sep, "/")
            out.append(f"- [{n.title}]({link}) &rarr; `[[{n.fm.get('superseded_by')}]]`")
        out.append("")

    if issues:
        errs = [i for i in issues if i.level == "ERROR"]
        out.append("## Integrity")
        out.append("")
        out.append(f"`kb.py lint` reports {len(errs)} error(s) and "
                   f"{len(issues) - len(errs)} warning(s):")
        out.append("")
        for i in issues:
            out.append(f"- `{i.rel}` **{i.field}** - {i.level}: {i.msg}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------

def cmd_index(root: str, notes: list[Note], arts) -> int:
    issues = validate(root, notes, arts) + ticket_docs_issues(root, notes, arts)
    path = os.path.join(kb_dir(root), "INDEX.md")
    content = render_index(root, notes, issues)
    old = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            old = fh.read()
    if old != content:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
    errs = sum(1 for i in issues if i.level == "ERROR")
    print(f"kb index: {len(notes)} note(s), {errs} error(s), "
          f"{len(issues) - errs} warning(s)"
          f"{'' if old == content else ' - INDEX.md updated'}")
    return 2 if issues else 0


def cmd_lint(root: str, notes: list[Note], arts) -> int:
    issues = validate(root, notes, arts) + ticket_docs_issues(root, notes, arts)
    for i in issues:
        print(i)
    if not issues:
        print(f"kb lint: clean ({len(notes)} note(s))")
    return 2 if issues else 0


SKELETON = {
    "business-rule": {
        "Rule": "State the rule as an imperative the code must obey. One rule per note.",
        "Why": "The product or legal reason. Without this the rule reads as an accident and gets refactored away.",
        "Where enforced": "The file and the layer that enforces it, and the test that guards it - or the fact that nothing does.",
    },
    "troubleshooting": {
        "Symptom": "What was observed, in the words of whoever hit it.",
        "Root cause": "The actual mechanism. Not 'a bug in X'.",
        "Fix": "What was changed, and in which ticket.",
        "How to detect it again": "The command, log line or metric that shows this recurring.",
    },
    "overview": {
        "What it does": "The module's responsibility in two or three sentences.",
        "Structure": "The pieces and how they relate. Name paths, do not paste code.",
        "Entry points": "Routes, commands, jobs, components - where execution enters.",
    },
    "integration": {
        "What it is": "The external system and what we use it for.",
        "How we call it": "Credentials, client, retries, timeouts, where the code lives.",
        "Behaviour to know": "The surprises: eventual consistency, silent truncation, undocumented limits.",
    },
    "api-contract": {
        "Endpoint": "Method and path, plus auth.",
        "Request": "Parameters and their types.",
        "Response": "The shape, field by field, with units and nullability.",
        "Consumers": "Which code on the other side of the boundary depends on this, and what breaks if it changes.",
    },
    "decision": {
        "Decision": "What was decided, in one sentence, in the present tense.",
        "Context": "The forces that made the obvious choice wrong.",
        "Alternatives considered": "What was rejected and why. This is what stops the decision being re-litigated.",
        "Consequences": "What this costs us, including what it makes harder.",
    },
    "runbook": {
        "When to run this": "The trigger, and the preconditions to check first.",
        "Steps": "Numbered, copy-pasteable commands with the directory each runs from.",
        "If it goes wrong": "The failure modes and how to back out.",
    },
    "data-model": {
        "Entities": "The tables or types, with the fields that carry meaning.",
        "Invariants": "What must always hold, and what enforces it.",
        "Relations": "Cardinality and cascade behaviour.",
    },
}


def cmd_new(root: str, notes: list[Note], arts, argv: list[str]) -> int:
    cfg = forgecfg.load(root)
    SCOPES = cfg.kb_scopes
    LOCKED = cfg.kb_locked_types
    ticket, title = None, None
    args = []
    i = 0
    while i < len(argv):
        if argv[i] == "--ticket" and i + 1 < len(argv):
            ticket = argv[i + 1]; i += 2; continue
        if argv[i] == "--title" and i + 1 < len(argv):
            title = argv[i + 1]; i += 2; continue
        args.append(argv[i]); i += 1
    if len(args) < 3:
        print('fatal: new <type> <scope> <description...> [--ticket ID] [--title "..."]',
              file=sys.stderr)
        return 1
    # the description may arrive quoted as one argument or as several words
    ntype, scope, desc = args[0], args[1], " ".join(args[2:])
    if ntype not in TYPES:
        print(f"fatal: unknown type '{ntype}', expected one of {sorted(TYPES)}", file=sys.stderr)
        return 1
    # a tracker scope is accepted and mapped to its knowledge-base scope
    if scope not in SCOPES and scope in cfg.scopes:
        scope = cfg.kb_scope_of(scope)
    if scope not in SCOPES:
        print(f"fatal: unknown scope '{scope}', expected one of {SCOPES}", file=sys.stderr)
        return 1
    if ntype in LOCKED and scope not in LOCKED[ntype]:
        print(f"fatal: type '{ntype}' may only live in {sorted(LOCKED[ntype])}", file=sys.stderr)
        return 1
    desc = re.sub(r"\s+", " ", desc.replace("_", " ").lower()).strip(" -")
    desc = re.sub(r" +", " ", re.sub(r"[^a-z0-9 -]", "", desc))
    if not DESC_RE.match(desc):
        print("fatal: the description must reduce to lowercase words separated by spaces",
              file=sys.stderr)
        return 1

    today = agile.datetime.now(agile.timezone.utc).strftime("%Y-%m-%d")
    base = f"{{{ntype}}} {desc} - {today}"
    if len(base) + 3 > MAX_BASENAME:
        print(f"fatal: '{base}.md' is {len(base) + 3} chars, the limit is {MAX_BASENAME} - "
              "shorten the description", file=sys.stderr)
        return 1
    if resolve(notes, base):
        print(f"fatal: {base}.md already exists - update it instead of creating a near-duplicate",
              file=sys.stderr)
        return 1
    if ticket and ticket not in {a.id for a in arts if a.id}:
        print(f"fatal: '{ticket}' does not resolve to an artifact in the tracker", file=sys.stderr)
        return 1

    d = os.path.join(kb_dir(root), scope, ntype)
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, base + ".md")

    fm = [
        "---",
        f"type: {ntype}",
        f"scope: {scope}",
        f"title: {title or desc.capitalize()}",
        "status: current",
        f"created: {today}",
        f"updated: {today}",
        f"tickets: [{ticket}]" if ticket else "tickets: []",
        "superseded_by: null",
        "labels: []",
        "---",
        "",
        f"# {title or desc.capitalize()}",
        "",
    ]
    body = []
    for heading, hint in SKELETON[ntype].items():
        body += [f"## {heading}", "", f"_{hint}_", ""]
    body += ["## Related", "", "- _none yet_", ""]

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(fm + body))
    print(os.path.relpath(path, root))
    if not title:
        print("note: `title:` is a placeholder - replace it with the finding as a sentence",
              file=sys.stderr)
    return 0


def cmd_find(root: str, notes: list[Note], argv: list[str]) -> int:
    if not argv:
        print("fatal: find needs at least one keyword", file=sys.stderr)
        return 1
    words = [w.lower() for w in argv]
    hits = []
    for n in notes:
        hay = "\n".join([n.base, n.title, " ".join(str(x) for x in n.listfield("labels")),
                         " ".join(str(x) for x in n.listfield("tickets")), n.body]).lower()
        if all(w in hay for w in words):
            where = "title" if all(w in (n.base + " " + n.title).lower() for w in words) else "body"
            hits.append((n, where))
    for n, where in sorted(hits, key=lambda h: (h[1] != "title", h[0].wrel)):
        print(f"{os.path.relpath(n.path, root)}\t{n.fm.get('type')}\t{n.title}\t[{where}]")
    if not hits:
        print(f"no note matches {words} - this is a gap, not an answer", file=sys.stderr)
        return 2
    return 0


def cmd_for_ticket(root: str, notes: list[Note], arts, ident: str) -> int:
    art = next((a for a in arts if a.id == ident), None)
    if art is None:
        print(f"fatal: no artifact with id '{ident}'", file=sys.stderr)
        return 1
    declared = [str(x) for x in art.listfield("docs")]
    backrefs = [n for n in notes if ident in [str(x) for x in n.listfield("tickets")]]
    print(f"{ident} ({art.kind}, scope {art.fm.get('scope')}, status {art.status})")
    print("docs: on the ticket:")
    for entry in declared or []:
        n = resolve(notes, entry)
        print(f"  {'OK ' if n else 'MISSING '} {entry}" + (f"\t{n.title}" if n else ""))
    if not declared:
        waiver = art.fm.get("docs_waiver")
        print(f"  (none){' - waiver: ' + str(waiver) if waiver else ' - and no waiver'}")
    print("notes claiming this ticket:")
    for n in sorted(backrefs, key=lambda n: n.wrel):
        print(f"  {os.path.relpath(n.path, root)}\t{n.title}")
    if not backrefs:
        print("  (none)")
    # A ticket may legitimately *read* a note without touching it - `tickets:`
    # records what produced or last confirmed the note, not who consulted it.
    # So an asymmetry is information, not a defect.
    read_only = [e for e in declared
                 if resolve(notes, e) and ident not in
                 [str(x) for x in resolve(notes, e).listfield("tickets")]]
    if read_only:
        print("read but not claimed (consulted, never updated by this ticket):")
        for e in read_only:
            print(f"  {e}")
    return 2 if [e for e in declared if not resolve(notes, e)] else 0


def cmd_show(root: str, notes: list[Note], ident: str) -> int:
    n = resolve(notes, ident)
    if n is None:
        print(f"fatal: no note matching '{ident}'", file=sys.stderr)
        return 1
    sections = [m.group(1).strip() for m in re.finditer(r"^##\s+(.+?)\s*$", n.body, re.MULTILINE)]
    print(json.dumps({"path": n.rel, "basename": n.base, "frontmatter": n.fm,
                      "sections": sections, "links": n.links()}, indent=2, sort_keys=True))
    return 0


def cmd_related(root: str, notes: list[Note], ident: str) -> int:
    n = resolve(notes, ident)
    if n is None:
        print(f"fatal: no note matching '{ident}'", file=sys.stderr)
        return 1
    by_base = {x.base: x for x in notes}
    print(f"{n.base}\t{n.title}")
    print("out:")
    for t in n.links():
        tgt = by_base.get(t)
        print(f"  {'->' if tgt else '?? '} {t}" + (f"\t{tgt.title}" if tgt else "\tUNRESOLVED"))
    if not n.links():
        print("  (none)")
    print("in:")
    inbound = [x for x in notes if n.base in x.links()]
    for x in sorted(inbound, key=lambda x: x.base):
        print(f"  <- {x.base}\t{x.title}")
    if not inbound:
        print("  (none)")
    one_sided = [t for t in n.related_links()
                 if t in by_base and n.base not in by_base[t].related_links()]
    for t in one_sided:
        print(f"warn: [[{t}]] does not link back - add the matching '## Related' line there",
              file=sys.stderr)
    return 2 if one_sided else 0


def cmd_types(root: str) -> int:
    cfg = forgecfg.load(root)
    print(f"scopes: {', '.join(cfg.kb_scopes)}")
    for t in sorted(TYPES):
        locked = cfg.kb_locked_types.get(t)
        lock = f"  [{'/'.join(sorted(locked))} only]" if locked else ""
        print(f"{t}{lock}\n  sections: " + " | ".join(TYPES[t] + ["Related"]))
    return 0


USAGE = __doc__


def main(argv: list[str]) -> int:
    args = list(argv[1:])
    root_arg = None
    if "--root" in args:
        i = args.index("--root")
        try:
            root_arg = args[i + 1]
        except IndexError:
            print("fatal: --root needs a path", file=sys.stderr)
            return 1
        del args[i:i + 2]
    if not args or args[0] in ("-h", "--help", "help"):
        print(USAGE)
        return 0 if args else 1

    root = agile.find_root(root_arg)
    cmd = args[0]
    if cmd == "types":
        return cmd_types(root)

    notes, fatal = load_notes(root)
    arts, afatal = agile.load_all(root)
    if fatal or afatal:
        for f in fatal + afatal:
            print(f"fatal: {f}", file=sys.stderr)
        return 1

    if cmd == "index":
        return cmd_index(root, notes, arts)
    if cmd == "lint":
        return cmd_lint(root, notes, arts)
    if cmd == "new":
        return cmd_new(root, notes, arts, args[1:])
    if cmd == "find":
        return cmd_find(root, notes, args[1:])
    if cmd == "for-ticket":
        if len(args) < 2:
            print("fatal: for-ticket needs a ticket ID", file=sys.stderr)
            return 1
        return cmd_for_ticket(root, notes, arts, args[1])
    if cmd == "show":
        if len(args) < 2:
            print("fatal: show needs a basename or path", file=sys.stderr)
            return 1
        return cmd_show(root, notes, args[1])
    if cmd == "related":
        if len(args) < 2:
            print("fatal: related needs a basename or path", file=sys.stderr)
            return 1
        return cmd_related(root, notes, args[1])
    print(f"fatal: unknown command '{cmd}'", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
