#!/usr/bin/env python3
"""lessons.py - what this project taught its agents, in a form they can afford to read.

`docs/agile/` records what we are doing and `docs/knowledge/` what we know about
the product. This records **how work goes wrong here**: the rule a ticket paid
for by bouncing off a gate. One rule per file, one line per rule.

The one-line `rule:` is the whole design. It is what an agent is handed at the
start of a gate; the body is read only when the line turns out to matter. A
layer that cannot be read cheaply is a layer that does not get read, so the
budget in `for` is a hard cap, not a suggestion, and `lint` refuses a rule that
does not fit on a line.

Stdlib only. Shares agile.py's frontmatter grammar, so a lesson, a ticket and a
knowledge-base note are all parsed by the same restricted reader.

Commands
    for <agent|role|scope>      the rules that agent must obey, ranked and capped
                                  [--scope S] [--budget N] [--paths]
    list [--scope S] [--role R] [--retired]
                                one line per lesson
    show <LESSON-NNNN>          the whole file, path first
    new "<description>" --scope S --roles r,r [--rule "..."]
                                  [--ticket ID] [--gate N]
    confirm <LESSON-NNNN> [--ticket ID]
                                this lesson just proved itself again
    retire <LESSON-NNNN> --reason "..."
    supersede <LESSON-NNNN> --by <LESSON-NNNN>
    audit                       the decision queue: every active rule with its age,
                                  its weight and who the budget hides it from
    lint                        validate only, print PATH:FIELD: LEVEL: MESSAGE
    index                       regenerate <lessons>/INDEX.md
    roles                       print the legal scope/role vocabulary

Exit codes
    0  clean
    1  fatal (unreadable file, bad arguments)
    2  integrity issues found (index still written)
"""

from __future__ import annotations

import datetime
import os
import re
import sys

sys.dont_write_bytecode = True   # never leave __pycache__ in the repo
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import agile     # noqa: E402  - same directory, shares the frontmatter grammar
import forge as forgecfg  # noqa: E402

ROLES = forgecfg.LESSON_ROLES
ALL = forgecfg.LESSON_ALL

STATUSES = ["active", "retired", "superseded"]

REQUIRED_FIELDS = [
    "id", "scope", "roles", "rule", "status", "gate",
    "tickets", "confirmations", "last_confirmed",
    "created", "updated", "superseded_by",
]

# A lesson is addressed by its id, not by its basename: a ticket carries
# `lessons: [LESSON-0003]` and an agent is handed the same token back. That is
# why the filename leads with the id and drops the knowledge base's braced type
# and trailing date - there is only one type here, and the date is in the
# frontmatter where nothing has to re-read a path to get at it.
ID_RE = re.compile(r"^LESSON-\d{4}$")
NAME_RE = re.compile(r"^(?P<id>LESSON-\d{4}) (?P<desc>[a-z0-9][a-z0-9 -]*)$")
DESC_RE = re.compile(r"^[a-z0-9]+(?:[ -][a-z0-9]+)*$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+?)(?:\|[^\]]*)?\]\]")

MAX_BASENAME = 72
# The rule has to survive being quoted inside somebody else's prompt. One line.
MAX_RULE = 120
MIN_RULE = 20
# Not a style rule: every line here is paid for out of the agent's context on
# the turn it reads the file. A lesson that needs an essay is a knowledge-base
# note wearing a lesson's hat.
MAX_BODY_LINES = 40

SECTIONS = ["Why", "How to apply", "Evidence"]

BANNER = (
    "<!-- GENERATED by .claude/scripts/lessons.py - DO NOT EDIT. "
    "Run: python3 .claude/scripts/lessons.py index -->"
)


def today() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")


def days_since(iso: str) -> int | None:
    if not DATE_RE.match(str(iso)):
        return None
    try:
        then = datetime.date.fromisoformat(str(iso))
    except ValueError:
        return None
    return (datetime.date.today() - then).days


# --------------------------------------------------------------------------
# loading
# --------------------------------------------------------------------------

class Lesson(agile.Artifact):
    """One rule. Inherits has_section / listfield / section from agile.Artifact."""

    def __init__(self, path, rel, wrel, fm, body):
        super().__init__(path, rel, fm, body)
        self.wrel = wrel                                  # relative to the lessons root
        self.base = os.path.basename(rel)[:-3]            # basename, no .md
        parts = wrel.split(os.sep)
        self.dir_scope = parts[0] if len(parts) > 1 else None

    @property
    def rule(self) -> str:
        return str(self.fm.get("rule") or "")

    @property
    def lscope(self) -> str:
        return str(self.fm.get("scope") or "")

    @property
    def roles(self) -> list[str]:
        return [str(r) for r in self.listfield("roles")]

    @property
    def confirmations(self) -> int:
        try:
            return int(self.fm.get("confirmations") or 0)
        except (TypeError, ValueError):
            return -1

    def addresses(self, scope: str | None, role: str | None) -> bool:
        """Does this lesson speak to that audience? A missing axis matches
        everything, which is what makes `for <scope>` and `for <role>` useful
        on their own."""
        if scope is not None and self.lscope not in (scope, ALL):
            return False
        if role is not None and role not in self.roles and ALL not in self.roles:
            return False
        return True

    def weight(self) -> tuple:
        """Ranking key for the budgeted hand-off: a rule that has caught the
        same mistake four times outranks one filed yesterday, and a rule nobody
        has confirmed in a year sinks below both."""
        return (-self.confirmations, str(self.fm.get("last_confirmed") or ""), self.id)

    def links(self) -> list[str]:
        seen, out = set(), []
        for m in WIKILINK_RE.finditer(self.body):
            target = m.group(1).strip()
            if target.endswith(".md"):
                target = target[:-3]
            target = os.path.basename(target)
            if target and target not in seen:
                seen.add(target)
                out.append(target)
        return out


def lessons_dir(root: str) -> str:
    return forgecfg.load(root).lessons_dir()


def load_lessons(root: str) -> tuple[list[Lesson], list[str]]:
    cfg = forgecfg.load(root)
    base = cfg.lessons_dir()
    if not os.path.isdir(base):
        raise SystemExit(
            f"fatal: {base} does not exist - run `forge upgrade` to create it, "
            f"then see {cfg.lessons_rel}/README.md"
        )
    out: list[Lesson] = []
    fatal: list[str] = []
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for name in sorted(filenames):
            if not name.endswith(".md") or name.startswith("."):
                continue
            if name in ("README.md", "INDEX.md") and os.path.samefile(dirpath, base):
                continue
            path = os.path.join(dirpath, name)
            rel = os.path.relpath(path, root)
            wrel = os.path.relpath(path, base)
            try:
                with open(path, encoding="utf-8") as fh:
                    text = fh.read()
                fm = agile.parse_frontmatter(text)
            except (OSError, agile.ParseError) as exc:
                fatal.append(f"{rel}: {exc}")
                continue
            out.append(Lesson(path, rel, wrel, fm, text.split("\n---", 1)[-1]))
    return out, fatal


def resolve(lessons: list[Lesson], ident: str) -> Lesson | None:
    ident = str(ident).strip()
    if ident.endswith(".md"):
        ident = ident[:-3]
    for l in lessons:
        if l.id == ident:
            return l
    for l in lessons:
        if l.base == os.path.basename(ident) or ident in (l.wrel[:-3], l.rel[:-3]):
            return l
    return None


# --------------------------------------------------------------------------
# validation
# --------------------------------------------------------------------------

def validate(root: str, lessons: list[Lesson], arts: list[agile.Artifact]) -> list[agile.Issue]:
    cfg = forgecfg.load(root)
    issues: list[agile.Issue] = []
    scopes = cfg.lesson_scopes()
    ticket_ids = {a.id for a in arts if a.id}
    ngates = len(agile.GATES)

    def err(l, field, msg):
        issues.append(agile.Issue(l.rel, field, msg))

    def warn(l, field, msg):
        issues.append(agile.Issue(l.rel, field, msg, "WARN"))

    by_id: dict[str, Lesson] = {}
    for l in lessons:
        if not ID_RE.match(l.id):
            err(l, "id", f"'{l.id}' is not LESSON-NNNN")
        elif l.id in by_id:
            err(l, "id", f"duplicate id, also used by {by_id[l.id].rel}")
        else:
            by_id[l.id] = l

    for l in lessons:
        # ---- location and filename ----------------------------------------
        if l.dir_scope is None:
            err(l, "path", f"a lesson lives at {cfg.lessons_rel}/<scope>/<file>.md, never higher")
            continue
        if l.dir_scope not in scopes:
            err(l, "path", f"'{l.dir_scope}' is not one of {scopes}")
        m = NAME_RE.match(l.base)
        if not m:
            err(l, "filename", "must be 'LESSON-NNNN <description>.md' - lowercase "
                               "words after the id, no date (it is in the frontmatter)")
        else:
            if m.group("id") != l.id:
                err(l, "filename", f"'{m.group('id')}' contradicts id: {l.id}")
            if not DESC_RE.match(m.group("desc")):
                err(l, "filename",
                    f"description '{m.group('desc')}' must be lowercase words separated by spaces")
        if len(os.path.basename(l.rel)) > MAX_BASENAME:
            err(l, "filename", f"{len(os.path.basename(l.rel))} chars, the limit is {MAX_BASENAME}")

        # ---- frontmatter --------------------------------------------------
        for f in REQUIRED_FIELDS:
            if f not in l.fm:
                err(l, f, "field is missing")

        if l.lscope not in scopes:
            err(l, "scope", f"'{l.lscope}' is not one of {scopes}")
        elif l.dir_scope in scopes and l.lscope != l.dir_scope:
            err(l, "scope", f"'{l.lscope}' contradicts the folder '{l.dir_scope}'")

        roles = l.roles
        if not roles:
            err(l, "roles", f"name the identities that must obey this: {list(ROLES)} or [{ALL}]")
        for r in roles:
            if r not in ROLES and r != ALL:
                err(l, "roles", f"'{r}' is not one of {list(ROLES)} or '{ALL}'")
        if ALL in roles and len(roles) > 1:
            err(l, "roles", f"'{ALL}' already means every role - drop the rest")

        rule = l.rule
        if not rule:
            err(l, "rule", "must state the rule as one imperative line - it is what an "
                           "agent is handed, and an empty one costs context for nothing")
        else:
            if "\n" in rule:
                err(l, "rule", "must be a single line")
            if len(rule) > MAX_RULE:
                err(l, "rule", f"{len(rule)} chars, the limit is {MAX_RULE} - "
                               "the detail belongs in '## How to apply'")
            elif len(rule) < MIN_RULE:
                warn(l, "rule", "too short to be actionable - state what to do, not a topic")

        if l.status not in STATUSES:
            err(l, "status", f"'{l.status}' is not one of {STATUSES}")

        gate = l.fm.get("gate")
        if gate is not None:
            try:
                g = int(gate)
            except (TypeError, ValueError):
                g = -1
            if not 1 <= g <= ngates:
                err(l, "gate", f"'{gate}' is not a gate number (1-{ngates}) or null")

        if l.confirmations < 0:
            err(l, "confirmations", "must be a non-negative integer")

        for f in ("created", "updated", "last_confirmed"):
            v = l.fm.get(f)
            if v is None:
                err(l, f, "must be a date")
            elif not DATE_RE.match(str(v)):
                err(l, f, f"'{v}' is not YYYY-MM-DD")
        cre = str(l.fm.get("created"))
        for f in ("updated", "last_confirmed"):
            v = str(l.fm.get(f))
            if DATE_RE.match(cre) and DATE_RE.match(v) and v < cre:
                err(l, f, f"'{v}' precedes created '{cre}'")

        # ---- provenance ---------------------------------------------------
        tickets = l.listfield("tickets")
        if not tickets:
            warn(l, "tickets", "no ticket recorded - which failure paid for this rule?")
        for t in tickets:
            if str(t) not in ticket_ids:
                err(l, "tickets", f"'{t}' does not resolve to an artifact in the tracker")

        sb = l.fm.get("superseded_by")
        if l.status == "superseded":
            if not sb:
                err(l, "superseded_by", "a superseded lesson must point at its replacement")
            elif not resolve(lessons, str(sb)):
                err(l, "superseded_by", f"'{sb}' does not resolve to a lesson")
        elif sb:
            err(l, "superseded_by", "set only when status is 'superseded'")

        # ---- body ---------------------------------------------------------
        for heading in SECTIONS:
            if not re.search(r"^##\s+" + re.escape(heading) + r"\s*$", l.body, re.MULTILINE):
                err(l, "body", f"missing section '## {heading}'")
            elif not l.has_section(heading):
                err(l, "body", f"section '## {heading}' is empty or a placeholder")
        if not re.search(r"^##\s+Related\s*$", l.body, re.MULTILINE):
            err(l, "body", "missing section '## Related' - keep it with '- _none yet_' if empty")
        nlines = len([x for x in l.body.splitlines() if x.strip()])
        if nlines > MAX_BODY_LINES:
            warn(l, "body", f"{nlines} non-empty lines, the budget is {MAX_BODY_LINES} - "
                            "an agent pays for every one of them; move the background "
                            f"into {cfg.kb_rel}/ and link it")

        # A link to a lesson must resolve; a link to anything else is a
        # knowledge-base note and is not this script's tree to police.
        for target in l.links():
            if target == l.id or target == l.base:
                err(l, "links", "a lesson must not link to itself")
            elif ID_RE.match(target) and target not in by_id:
                err(l, "links", f"[[{target}]] does not resolve to a lesson")

        # ---- decay ---------------------------------------------------------
        if l.status == "active":
            age = days_since(l.fm.get("last_confirmed"))
            if age is not None and age > cfg.lesson_stale_days:
                warn(l, "last_confirmed",
                     f"{age} days since this was last confirmed (budget "
                     f"{cfg.lesson_stale_days}) - confirm it or retire it; a rule "
                     "nobody has needed in that long is spending context for nothing")

    # ---- duplication ------------------------------------------------------
    seen: dict[str, Lesson] = {}
    for l in sorted((x for x in lessons if x.status == "active"), key=lambda x: x.id):
        key = re.sub(r"[^a-z0-9 ]", "", l.rule.lower()).strip()
        if not key:
            continue
        if key in seen:
            warn(l, "rule", f"reads the same as {seen[key].id} - supersede one of them")
        else:
            seen[key] = l

    return sorted(issues, key=lambda i: (i.rel, i.field))


def ticket_lesson_issues(root: str, lessons: list[Lesson],
                         arts: list[agile.Artifact]) -> list[agile.Issue]:
    """The tracker half of the contract. agile.py owns the authoritative check;
    this mirrors it so `lessons.py lint` alone shows a broken ticket->lesson edge."""
    issues: list[agile.Issue] = []
    for a in arts:
        if a.kind not in ("task", "bug"):
            continue
        for entry in a.listfield("lessons"):
            if not resolve(lessons, str(entry)):
                issues.append(agile.Issue(a.rel, "lessons",
                                          f"'{entry}' does not resolve to a lesson"))
    return issues


# --------------------------------------------------------------------------
# frontmatter rewriting - the restricted grammar, one line per key
# --------------------------------------------------------------------------

def set_fields(path: str, values: dict) -> None:
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise SystemExit(f"fatal: {path} has no frontmatter")
    end = next(i for i, l in enumerate(lines[1:], 1) if l.strip() == "---")
    for key, val in values.items():
        if isinstance(val, list):
            rendered = f"{key}: [" + ", ".join(str(v) for v in val) + "]"
        elif val is None:
            rendered = f"{key}: null"
        else:
            rendered = f"{key}: {val}"
        for i in range(1, end):
            if lines[i].split(":", 1)[0].strip() == key:
                lines[i] = rendered
                break
        else:
            lines.insert(end, rendered)
            end += 1
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def append_to_section(path: str, heading: str, line: str) -> None:
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    m = re.search(r"^##\s+" + re.escape(heading) + r"\s*$", text, re.MULTILINE)
    if not m:
        return
    rest = text[m.end():]
    nxt = re.search(r"^##\s+", rest, re.MULTILINE)
    cut = m.end() + (nxt.start() if nxt else len(rest))
    chunk = text[m.end():cut].rstrip("\n")
    text = text[:m.end()] + chunk + "\n" + line + "\n\n" + text[cut:].lstrip("\n")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


# --------------------------------------------------------------------------
# INDEX.md
# --------------------------------------------------------------------------

def render_index(root: str, lessons: list[Lesson], issues: list[agile.Issue]) -> str:
    cfg = forgecfg.load(root)
    active = [l for l in lessons if l.status == "active"]
    gone = [l for l in lessons if l.status != "active"]

    out = [BANNER, "", "# Lessons", "",
           f"What {cfg.project_name} has taught its agents, by scope. One rule per file;",
           "the rule itself is the whole index entry. The convention is in",
           "[`README.md`](README.md).", "",
           f"{len(lessons)} lesson(s): {len(active)} active, {len(gone)} retired or superseded.",
           ""]

    for scope in cfg.lesson_scopes():
        here = sorted((l for l in active if l.lscope == scope), key=lambda l: l.weight())
        if not here:
            continue
        out += [f"## {scope}", "",
                "| | Rule | Roles | Gate | Confirmed |", "|---|---|---|---|---|"]
        for l in here:
            link = l.wrel.replace(os.sep, "/")
            gate = l.fm.get("gate")
            out.append(f"| [`{l.id}`]({link}) | {l.rule} | {', '.join(l.roles)} | "
                       f"{gate if gate is not None else '&ndash;'} | "
                       f"{l.fm.get('last_confirmed')} &times;{l.confirmations} |")
        out.append("")

    if gone:
        out += ["## Retired and superseded", ""]
        for l in sorted(gone, key=lambda l: l.id):
            link = l.wrel.replace(os.sep, "/")
            tail = (f" &rarr; `{l.fm.get('superseded_by')}`"
                    if l.status == "superseded" else "")
            out.append(f"- [`{l.id}`]({link}) _{l.status}_ &middot; {l.rule}{tail}")
        out.append("")

    if issues:
        errs = [i for i in issues if i.level == "ERROR"]
        out += ["## Integrity", "",
                f"`lessons.py lint` reports {len(errs)} error(s) and "
                f"{len(issues) - len(errs)} warning(s):", ""]
        for i in issues:
            out.append(f"- `{i.rel}` **{i.field}** - {i.level}: {i.msg}")
        out.append("")

    credit = cfg.credit()
    if credit:
        out += ["---", "", credit, ""]
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------

def _flag(argv: list[str], name: str, default=None):
    if name in argv:
        i = argv.index(name)
        if i + 1 < len(argv):
            return argv[i + 1]
    return default


def _strip_flags(argv: list[str], names: tuple[str, ...]) -> list[str]:
    out, i = [], 0
    while i < len(argv):
        if argv[i] in names:
            i += 2
            continue
        if argv[i].startswith("--"):
            i += 1
            continue
        out.append(argv[i])
        i += 1
    return out


def rules_for(root: str, who: str | None, scope: str | None = None,
              budget: int | None = None) -> tuple[list[Lesson], list[Lesson], str]:
    """The rules binding one audience: (shown, withheld, how to name them).

    Factored out of `cmd_for` so that `agile.py handoff` can render the same
    ranked, capped list straight into a dispatch payload. One ranking, one cap,
    one place - a second implementation would drift, and the budget is the
    whole reason this layer is affordable.

    Raises ValueError when `who` names nothing the project has.
    """
    cfg = forgecfg.load(root)
    role = None
    if who:
        if who in cfg.agents or who in forgecfg.AGENT_ALIASES:
            role = cfg.role_of_agent(who)
            scope = scope or cfg.scope_of_agent(who)
        elif who in ROLES:
            role = who
        elif who in cfg.scopes:
            scope = scope or who
        elif who != ALL:
            raise ValueError(
                f"'{who}' is not an agent, a role {list(ROLES)} or a scope "
                f"{list(cfg.scopes)}")
    if budget is None:
        budget = cfg.lesson_budget
    budget = max(1, budget)

    lessons, _fatal = load_lessons(root)
    pool = [l for l in lessons if l.status == "active" and l.addresses(scope, role)]
    pool.sort(key=lambda l: l.weight())
    audience = " / ".join(x for x in (scope, role) if x) or "every agent"
    return pool[:budget], pool[budget:], audience


def cmd_for(root: str, lessons: list[Lesson], argv: list[str]) -> int:
    """The hot path: what one agent must obey, ranked and capped.

    Never fails. It runs at the top of a gate, and an agent that reads a
    non-zero exit here learns to stop running it."""
    cfg = forgecfg.load(root)
    rest = _strip_flags(argv, ("--scope", "--budget"))
    who = rest[0] if rest else None
    try:
        budget = max(1, int(_flag(argv, "--budget", cfg.lesson_budget)))
    except (TypeError, ValueError):
        budget = cfg.lesson_budget
    try:
        shown, withheld, audience = rules_for(root, who, _flag(argv, "--scope"), budget)
    except ValueError as exc:
        print(f"fatal: {exc}", file=sys.stderr)
        return 1
    pool = shown + withheld
    if not pool:
        print(f"lessons for {audience}: none recorded yet.")
        return 0
    print(f"{len(shown)} lesson(s) for {audience}"
          f"{f' - {len(withheld)} more withheld, lowest-ranked first' if withheld else ''}. "
          "These are rules this project paid for; obey them unless the ticket says otherwise.")
    want_paths = "--paths" in argv
    for l in shown:
        line = f"  {l.id}  {l.rule}"
        if want_paths:
            line += f"\n      {l.rel}"
        print(line)
    if withheld:
        # Naming all of them would make this line grow without bound, which is
        # the thing the budget exists to prevent. The count is the part that
        # must never be dropped; the ids are a courtesy.
        named = withheld[:5]
        tail = f", and {len(withheld) - len(named)} more" if len(withheld) > len(named) else ""
        print(f"  (withheld: {', '.join(l.id for l in named)}{tail} - "
              f"`lessons.py list` shows all of them)")
    print("Why one of them exists: python3 .claude/scripts/lessons.py show <LESSON-NNNN>")
    return 0


def cmd_list(root: str, lessons: list[Lesson], argv: list[str]) -> int:
    scope = _flag(argv, "--scope")
    role = _flag(argv, "--role")
    pool = [l for l in lessons if l.addresses(scope, role)]
    if "--retired" not in argv:
        pool = [l for l in pool if l.status == "active"]
    for l in sorted(pool, key=lambda l: (l.lscope, l.weight())):
        print(f"{l.id}\t{l.lscope}\t{','.join(l.roles)}\t{l.status}\t"
              f"x{l.confirmations}\t{l.rule}")
    if not pool:
        print("no lesson matches", file=sys.stderr)
        return 2
    return 0


def cmd_show(root: str, lessons: list[Lesson], ident: str) -> int:
    l = resolve(lessons, ident)
    if l is None:
        print(f"fatal: no lesson matching '{ident}'", file=sys.stderr)
        return 1
    print(f"# {l.rel}")
    with open(l.path, encoding="utf-8") as fh:
        sys.stdout.write(fh.read())
    return 0


SKELETON = {
    "Why": "The failure this prevents, named concretely. A rule whose reason is "
           "invisible gets optimised away by the next agent.",
    "How to apply": "What to do differently, as steps or a command. Not advice - an action.",
    "Evidence": "The ticket and the gate it bounced off, one line each.",
}


def next_id(lessons: list[Lesson]) -> str:
    used = [int(l.id.split("-")[1]) for l in lessons if ID_RE.match(l.id)]
    return f"LESSON-{max(used, default=0) + 1:04d}"


def cmd_new(root: str, lessons: list[Lesson], arts, argv: list[str]) -> int:
    cfg = forgecfg.load(root)
    scope = _flag(argv, "--scope")
    roles = _flag(argv, "--roles")
    rule = _flag(argv, "--rule")
    ticket = _flag(argv, "--ticket")
    gate = _flag(argv, "--gate")
    rest = _strip_flags(argv, ("--scope", "--roles", "--rule", "--ticket", "--gate"))
    if not rest or not scope or not roles:
        print('fatal: new "<description>" --scope <scope|all> --roles <role,role|all> '
              '[--rule "..."] [--ticket ID] [--gate N]', file=sys.stderr)
        return 1
    if scope not in cfg.lesson_scopes():
        print(f"fatal: unknown scope '{scope}', expected one of {cfg.lesson_scopes()}",
              file=sys.stderr)
        return 1
    rl = [r.strip() for r in str(roles).split(",") if r.strip()]
    for r in rl:
        if r not in ROLES and r != ALL:
            print(f"fatal: unknown role '{r}', expected {list(ROLES)} or '{ALL}'",
                  file=sys.stderr)
            return 1
    if ticket and ticket not in {a.id for a in arts if a.id}:
        print(f"fatal: '{ticket}' does not resolve to an artifact in the tracker",
              file=sys.stderr)
        return 1
    if gate is not None:
        try:
            if not 1 <= int(gate) <= len(agile.GATES):
                raise ValueError
        except ValueError:
            print(f"fatal: --gate takes 1-{len(agile.GATES)}", file=sys.stderr)
            return 1

    desc = " ".join(rest)
    desc = re.sub(r"\s+", " ", desc.replace("_", " ").lower()).strip(" -")
    desc = re.sub(r" +", " ", re.sub(r"[^a-z0-9 -]", "", desc))
    if not DESC_RE.match(desc):
        print("fatal: the description must reduce to lowercase words separated by spaces",
              file=sys.stderr)
        return 1
    lid = next_id(lessons)
    base = f"{lid} {desc}"
    if len(base) + 3 > MAX_BASENAME:
        print(f"fatal: '{base}.md' is {len(base) + 3} chars, the limit is {MAX_BASENAME} - "
              "shorten the description", file=sys.stderr)
        return 1

    stamp = today()
    d = os.path.join(cfg.lessons_dir(), scope)
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, base + ".md")
    if os.path.exists(path):
        print(f"fatal: {path} already exists", file=sys.stderr)
        return 1

    fm = [
        "---",
        f"id: {lid}",
        f"scope: {scope}",
        f"roles: [{', '.join(rl)}]",
        f"rule: {rule or desc.capitalize() + ' - REPLACE THIS WITH THE RULE'}",
        "status: active",
        f"gate: {int(gate) if gate is not None else 'null'}",
        f"tickets: [{ticket}]" if ticket else "tickets: []",
        "confirmations: 0",
        f"last_confirmed: {stamp}",
        f"created: {stamp}",
        f"updated: {stamp}",
        "superseded_by: null",
        "---",
        "",
    ]
    body = []
    for heading in SECTIONS:
        body += [f"## {heading}", "", f"_{SKELETON[heading]}_", ""]
    body += ["## Related", "", "- _none yet_", ""]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(fm + body))
    print(os.path.relpath(path, root))
    if not rule:
        print("note: `rule:` is a placeholder - replace it with one imperative line. "
              "It is the only part most agents will ever read.", file=sys.stderr)
    return 0


def cmd_confirm(root: str, lessons: list[Lesson], arts, argv: list[str]) -> int:
    rest = _strip_flags(argv, ("--ticket",))
    if not rest:
        print("fatal: confirm <LESSON-NNNN> [--ticket ID]", file=sys.stderr)
        return 1
    l = resolve(lessons, rest[0])
    if l is None:
        print(f"fatal: no lesson matching '{rest[0]}'", file=sys.stderr)
        return 1
    ticket = _flag(argv, "--ticket")
    if ticket and ticket not in {a.id for a in arts if a.id}:
        print(f"fatal: '{ticket}' does not resolve to an artifact in the tracker",
              file=sys.stderr)
        return 1
    stamp = today()
    values = {"confirmations": l.confirmations + 1,
              "last_confirmed": stamp, "updated": stamp}
    if ticket:
        tickets = [str(t) for t in l.listfield("tickets")]
        if ticket not in tickets:
            values["tickets"] = tickets + [ticket]
    set_fields(l.path, values)
    print(f"{l.id} confirmed ({l.confirmations + 1}x, {stamp})")
    return 0


def cmd_retire(root: str, lessons: list[Lesson], argv: list[str]) -> int:
    rest = _strip_flags(argv, ("--reason",))
    reason = _flag(argv, "--reason")
    if not rest or not reason:
        print('fatal: retire <LESSON-NNNN> --reason "..."', file=sys.stderr)
        return 1
    l = resolve(lessons, rest[0])
    if l is None:
        print(f"fatal: no lesson matching '{rest[0]}'", file=sys.stderr)
        return 1
    stamp = today()
    set_fields(l.path, {"status": "retired", "updated": stamp})
    append_to_section(l.path, "Evidence", f"- retired {stamp}: {reason}")
    print(f"{l.id} retired")
    return 0


def cmd_supersede(root: str, lessons: list[Lesson], argv: list[str]) -> int:
    rest = _strip_flags(argv, ("--by",))
    by = _flag(argv, "--by")
    if not rest or not by:
        print("fatal: supersede <LESSON-NNNN> --by <LESSON-NNNN>", file=sys.stderr)
        return 1
    l, repl = resolve(lessons, rest[0]), resolve(lessons, by)
    if l is None or repl is None:
        print(f"fatal: no lesson matching '{rest[0] if l is None else by}'", file=sys.stderr)
        return 1
    if l.id == repl.id:
        print("fatal: a lesson cannot supersede itself", file=sys.stderr)
        return 1
    stamp = today()
    set_fields(l.path, {"status": "superseded", "superseded_by": repl.id, "updated": stamp})
    append_to_section(l.path, "Evidence", f"- superseded {stamp} by [[{repl.id}]]")
    print(f"{l.id} superseded by {repl.id}")
    return 0


def cmd_audit(root: str, lessons: list[Lesson], arts) -> int:
    """What a retrospective has to decide, and nothing it can decide alone.

    Every verdict here is a judgement - whether two rules are really the same
    rule, whether an unconfirmed one is stale or merely lucky - so this prints
    the queue and the evidence, and stops. `confirm`, `retire` and `supersede`
    are one call away and are deliberately not called from here."""
    cfg = forgecfg.load(root)
    live = [l for l in lessons if l.status == "active"]
    by_ticket_status = {a.id: a.status for a in arts if a.id}

    # Who actually receives what. The budget bites per audience, not per scope:
    # a rule filed under `all` can sit inside one agent's dozen and outside
    # another's, and reporting it by folder would hide exactly that.
    hidden_from: dict[str, list[str]] = {l.id: [] for l in live}
    for agent in cfg.agents:
        pool = sorted((l for l in live
                       if l.addresses(cfg.scope_of_agent(agent), cfg.role_of_agent(agent))),
                      key=lambda l: l.weight())
        for l in pool[cfg.lesson_budget:]:
            hidden_from[l.id].append(agent)

    print(f"{len(live)} active rule(s), budget {cfg.lesson_budget} per hand-off, "
          f"stale after {cfg.lesson_stale_days} days.")
    for scope in cfg.lesson_scopes():
        here = sorted((l for l in live if l.lscope == scope), key=lambda l: l.weight())
        if not here:
            continue
        print(f"\n## {scope}")
        for l in here:
            age = days_since(l.fm.get("last_confirmed"))
            flags = []
            if age is not None and age > cfg.lesson_stale_days:
                flags.append(f"STALE {age}d")
            if l.confirmations == 0 and (age or 0) > cfg.lesson_stale_days // 2:
                flags.append("NEVER CONFIRMED")
            if hidden_from[l.id]:
                flags.append("BELOW THE BUDGET, never reaches: " + ", ".join(hidden_from[l.id]))
            still_open = [t for t in (str(x) for x in l.listfield("tickets"))
                          if by_ticket_status.get(t) not in (None, "done", "cancelled",
                                                             "wontfix", "cannot_reproduce")]
            if still_open:
                flags.append("ticket still open: " + ", ".join(still_open))
            print(f"  {l.id}  x{l.confirmations}  {l.fm.get('last_confirmed')}  "
                  f"{'[' + '; '.join(flags) + ']' if flags else ''}")
            print(f"      {l.rule}")

    issues = [i for i in validate(root, lessons, arts)
              if i.level == "WARN" and i.field in ("rule", "last_confirmed")]
    if issues:
        print("\nWhat lint already suspects:")
        for i in issues:
            print(f"  {i.rel}\n    {i.msg}")
    print("\nNothing here is a verdict. Resolve each with confirm, retire or supersede.")
    return 0


def cmd_index(root: str, lessons: list[Lesson], arts) -> int:
    issues = validate(root, lessons, arts) + ticket_lesson_issues(root, lessons, arts)
    path = os.path.join(lessons_dir(root), "INDEX.md")
    content = render_index(root, lessons, issues)
    old = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            old = fh.read()
    if old != content:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
    errs = sum(1 for i in issues if i.level == "ERROR")
    print(f"lessons index: {len(lessons)} lesson(s), {errs} error(s), "
          f"{len(issues) - errs} warning(s)"
          f"{'' if old == content else ' - INDEX.md updated'}")
    return 2 if issues else 0


def cmd_lint(root: str, lessons: list[Lesson], arts) -> int:
    issues = validate(root, lessons, arts) + ticket_lesson_issues(root, lessons, arts)
    for i in issues:
        print(i)
    if not issues:
        print(f"lessons lint: clean ({len(lessons)} lesson(s))")
    return 2 if issues else 0


def cmd_roles(root: str) -> int:
    cfg = forgecfg.load(root)
    print(f"scopes: {', '.join(cfg.lesson_scopes())}   ('{ALL}' addresses every scope)")
    print(f"roles:  {', '.join(ROLES)}   ('{ALL}' addresses every role)")
    print(f"budget: {cfg.lesson_budget} rule(s) per hand-off, "
          f"stale after {cfg.lesson_stale_days} days")
    for agent in cfg.agents:
        print(f"  {agent:<20} role {cfg.role_of_agent(agent)}, "
              f"scope {cfg.scope_of_agent(agent) or 'all'}")
    return 0


USAGE = __doc__


def main(argv: list[str]) -> int:
    args = list(argv[1:])
    root_arg = None
    if "--root" in args:
        i = args.index("--root")
        try:
            root_arg = args[i + 1]
        except IndexError:
            print("fatal: --root needs a path", file=sys.stderr)
            return 1
        del args[i:i + 2]
    if not args or args[0] in ("-h", "--help", "help"):
        print(USAGE)
        return 0 if args else 1

    root = agile.find_root(root_arg)
    cmd = args[0]
    if cmd == "roles":
        return cmd_roles(root)

    lessons, fatal = load_lessons(root)
    if fatal:
        for f in fatal:
            print(f"fatal: {f}", file=sys.stderr)
        return 1
    if cmd == "for":
        return cmd_for(root, lessons, args[1:])
    if cmd == "list":
        return cmd_list(root, lessons, args[1:])
    if cmd == "show":
        if len(args) < 2:
            print("fatal: show needs a lesson id", file=sys.stderr)
            return 1
        return cmd_show(root, lessons, args[1])
    if cmd == "retire":
        return cmd_retire(root, lessons, args[1:])
    if cmd == "supersede":
        return cmd_supersede(root, lessons, args[1:])

    arts, afatal = agile.load_all(root)
    if afatal:
        for f in afatal:
            print(f"fatal: {f}", file=sys.stderr)
        return 1
    if cmd == "new":
        return cmd_new(root, lessons, arts, args[1:])
    if cmd == "confirm":
        return cmd_confirm(root, lessons, arts, args[1:])
    if cmd == "audit":
        return cmd_audit(root, lessons, arts)
    if cmd == "index":
        return cmd_index(root, lessons, arts)
    if cmd == "lint":
        return cmd_lint(root, lessons, arts)
    print(f"fatal: unknown command '{cmd}'", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
